image:
  repository: ghcr.io/den-vasyliev/kbot-src
  tag: sha-xxxxxx
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

app:
  name: kbot
  port: 8080

service:
  type: ClusterIP
  port: 8080

gateway:
  hostname: "kbot.example.com"
  parentGateway: "eg"
  weight: 1
dns:
  nameservers:
    - "1.1.1.1"

secretName: kbot
telegramTokenKey: token
